### ISSUE TITLE
Code wraps when code window is made narrow

### ISSUE THREAD

**Issue by hadley** [rstudio/profvis#7]
Instead I think it should just be truncated - I think you want

```css
td.code {
  white-space: pre-wrap; 
  overflow: hidden;
  text-overflow: ellipsis;
}
``` 

but I couldn't figure out quite the right selector to get it to work.

See https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow and http://caniuse.com/#search=text-overflow
